general:
  request-timeout: 15s
  tags:
     crabby-location: "Digitalocean SFO2"
     environment: prod
  report-internal-metrics: true
  internal-metrics-gathering-interval: 15
jobs:
 - name: my_app
   type: simple
   url: https://my-app-here/
   interval: 10
   tags:
      region: us-west-2
      isp: amazon
 - name: some_fancy_webpage
   type: selenium
   url:  https://my-site-here/some/page/
   interval: 30
   tags:
      region: us-central1
      isp: google
   cookies:
    - name: auth
      domain: mysite.org
      path: /
      value: DEADBEEFC0W123456789
      secure: true
    - name: session
      domain: mysite.org
      path: /
      value: abDijfeiF3290FijEIO30NC9jkqQER
      secure: false
 - name: my_api_endpoint
   type: api
   url: https://my-api-here/some/resource
   method: post
   body: >-
     { "hello": "world" }
   interval: 10
   tags:
     region: us-central1
     isp: google
#
# Selenium Configuration
#
# Remove/comment-out this section if you aren't using Selenium
# 
selenium:
 url: http://localhost:4444/wd/hub
 job-stagger-offset: 30
#
# Storage Backends
#
# You will need to remove/comment-out any that you are not going to be using.
# 
storage:
    graphite:
        host:  graphite.mysite.org
        port: 2003
        protocol: tcp
        metric-namespace: crabby.crabby-sfo-1
    dogstatsd:
        host: localhost
        port: 8125
        metric-namespace: crabby.crabby-sfo-1
        tags:
            - crabby-sfo-1
    prometheus:
        host: prometheus.mysite.org
        port: 9091
        metric-namespace: crabby.crabby-sfo-1
    riemann:
        host: riemann.mysite.org
        port: 5555
        metric-namespace: crabby.crabby-sfo-1
        tags:
            - crabby-sfo-1
